Neos:
  ContentRepositoryRegistry:
    nodeMigration:
      transformationFactories:
        ChangePropertyValueToLowercase: Visol\Neos\CaseInsensitiveUrls\Migration\Transformations\ChangePropertyValueToLowercaseFactory
